package UserInterface;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ChallengeBoardViewPage extends HorizontalLayout {
    protected CssLayout challBoaLevelLayout;
    protected Label challBoaLevelLabel;
    protected Button newChall;
    protected Button addLevelButton;
    protected Button back;
    protected CssLayout challBoaChallActiveLayout;
    protected Label challBoaActiveLabel;
    protected CssLayout challBoaChallPassiveLayout;
    protected Label challBoaPassivLabel;
    protected CssLayout challBoaChallDetailLayout;
    protected Label challBoaChallDetailsLabel;
    protected Panel details;

    public ChallengeBoardViewPage() {
        Design.read(this);
    }
}