package UserInterface;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ChallangeBoardView extends HorizontalLayout {
    protected VerticalLayout challBoaLevelLayout;
    protected Label challBoaLevelLabel;
    protected VerticalLayout challBoaChallOVLayout;
    protected HorizontalLayout challBoaChallAcPasLayout;
    protected Label challBoaChallAcLabel;
    protected Label challBoaChallPaLabel;
    protected VerticalLayout challBoaChallDetailLayout;
    protected Label challBoaChallDetailLabel;

    public ChallangeBoardView() {
        Design.read(this);
    }
}
