package UserInterface;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class JournalViewPage extends HorizontalLayout {
    protected VerticalLayout journalNavigationLayout;
    protected InlineDateField journalDate;
    protected Button newEntryButton;
    protected Button statisticsButton;
    protected Button tippsButton;
    protected Button backButton;
    protected VerticalLayout journalEntrysLayout;
    protected VerticalLayout journalDetailsLayout;

    public JournalViewPage() {
        Design.read(this);
    }
}
