package UserInterface;

<<<<<<< HEAD
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.navigator.View;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;

import java.util.ArrayList;
import java.util.List;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class JournalView extends HorizontalLayout implements View {
    private VerticalLayout journalNavigationLayout;
    private InlineDateField journalDate;
    private Button newEntryButton;
    private Button statisticsButton;
    private Button tippsButton;
    private VerticalLayout journalEntrysLayout;
    private VerticalLayout journalDetailsLayout;
    Button back = new Button("Back", this::buttonClick);
    public JournalView() {

        Design.read(this);
        this.newEntryButton.addClickListener(this::buttonClick);
        this.newEntryButton.setId("newEntryButton");
    }


    private List<Journal.JournalViewListener> listeners = new ArrayList<>();

    public void addListener(Journal.JournalViewListener listener) {
        listeners.add(listener);
    }

    public void buttonClick(Button.ClickEvent event) {
        for (Journal.JournalViewListener listener: listeners)
            listener.buttonClick(event.getButton());
    }

    public void addBackButton(){
        back.setId("back");
        back.setWidth("150px");
        journalNavigationLayout.addComponent(back);
        journalNavigationLayout.setComponentAlignment(back,Alignment.MIDDLE_CENTER);
    }
    public void addJournalEntry(String title, String desc) {
        Panel journal = new Panel(title);
        final VerticalLayout contentLayout = new VerticalLayout();
        contentLayout.addComponent(new Label(desc));
        journal.setContent(contentLayout);
        journal.setHeight("100%");
        journal.setWidth("100%");
    }
}
=======
public class JournalView extends JournalViewPage {
}
>>>>>>> master
