package UserInterface;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.CssLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class JournalViewPage extends HorizontalLayout {
    protected CssLayout journalNavigationLayout;
    protected InlineDateField journalDate;
    protected Button newEntryButton;
    protected Button statisticsButton;
    protected Button tippsButton;
    protected Button backButton;
    protected CssLayout journalEntrysLayout;
    protected CssLayout journalDetailsLayout;
    protected Panel details;

    public CssLayout getJournalNavigationLayout() {
        return journalNavigationLayout;
    }

    public InlineDateField getJournalDate() {
        return journalDate;
    }

    public Button getNewEntryButton() {
        return newEntryButton;
    }

    public Button getStatisticsButton() {
        return statisticsButton;
    }

    public Button getTippsButton() {
        return tippsButton;
    }

    public Button getBackButton() {
        return backButton;
    }

    public CssLayout getJournalEntrysLayout() {
        return journalEntrysLayout;
    }

    public CssLayout getJournalDetailsLayout() {
        return journalDetailsLayout;
    }

    public Panel getDetails() {
        return details;
    }

    public JournalViewPage() {
        Design.read(this);
    }

}
